[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-v --showlocals --durations 10 --timeout 1"
testpaths = ["tests"]
